# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lite.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlite.proto\x12\tliteproxy\"\xbc\x02\n\x0bTestRequest\x12\x11\n\tGroupName\x18\x01 \x01(\t\x12/\n\rSpeedTestMode\x18\x02 \x01(\x0e\x32\x18.liteproxy.SpeedTestMode\x12)\n\nPingMethod\x18\x03 \x01(\x0e\x32\x15.liteproxy.PingMethod\x12)\n\nSortMethod\x18\x04 \x01(\x0e\x32\x15.liteproxy.SortMethod\x12\x13\n\x0b\x43oncurrency\x18\x05 \x01(\x05\x12\x10\n\x08TestMode\x18\x06 \x01(\r\x12\x14\n\x0cSubscription\x18\x07 \x01(\t\x12\x10\n\x08Language\x18\x08 \x01(\t\x12\x10\n\x08\x46ontSize\x18\t \x01(\r\x12\r\n\x05Theme\x18\n \x01(\t\x12\x0f\n\x07Timeout\x18\x0b \x01(\x03\x12\x12\n\nOutputMode\x18\x0c \x01(\r\"\xac\x01\n\tTestReply\x12\n\n\x02Id\x18\x01 \x01(\x05\x12\x11\n\tGroupName\x18\x02 \x01(\t\x12\x0f\n\x07Remarks\x18\x03 \x01(\t\x12\x10\n\x08Protocol\x18\x04 \x01(\t\x12\x0c\n\x04Ping\x18\x05 \x01(\t\x12\x10\n\x08\x41vgSpeed\x18\x06 \x01(\x03\x12\x10\n\x08MaxSpeed\x18\x07 \x01(\x03\x12\x0c\n\x04IsOk\x18\x08 \x01(\x08\x12\x0f\n\x07Traffic\x18\t \x01(\x03\x12\x0c\n\x04Link\x18\n \x01(\t*5\n\rSpeedTestMode\x12\x0c\n\x08pingonly\x10\x00\x12\r\n\tspeedonly\x10\x01\x12\x07\n\x03\x61ll\x10\x02*)\n\nPingMethod\x12\x0e\n\ngoogleping\x10\x00\x12\x0b\n\x07tcpping\x10\x01*8\n\nSortMethod\x12\t\n\x05speed\x10\x00\x12\n\n\x06rspeed\x10\x01\x12\x08\n\x04ping\x10\x02\x12\t\n\x05rping\x10\x03\x32J\n\tTestProxy\x12=\n\tStartTest\x12\x16.liteproxy.TestRequest\x1a\x14.liteproxy.TestReply\"\x00\x30\x01\x42X\n\x1e\x63om.github.xxf098.api.rpc.liteB\tLiteProxyP\x01Z)github.com/xxf098/lite-proxy/api/rpc/liteb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lite_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036com.github.xxf098.api.rpc.liteB\tLiteProxyP\001Z)github.com/xxf098/lite-proxy/api/rpc/lite'
  _SPEEDTESTMODE._serialized_start=519
  _SPEEDTESTMODE._serialized_end=572
  _PINGMETHOD._serialized_start=574
  _PINGMETHOD._serialized_end=615
  _SORTMETHOD._serialized_start=617
  _SORTMETHOD._serialized_end=673
  _TESTREQUEST._serialized_start=26
  _TESTREQUEST._serialized_end=342
  _TESTREPLY._serialized_start=345
  _TESTREPLY._serialized_end=517
  _TESTPROXY._serialized_start=675
  _TESTPROXY._serialized_end=749
# @@protoc_insertion_point(module_scope)
