# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lite_pb2 as lite__pb2


class TestProxyStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartTest = channel.unary_stream(
                '/liteproxy.TestProxy/StartTest',
                request_serializer=lite__pb2.TestRequest.SerializeToString,
                response_deserializer=lite__pb2.TestReply.FromString,
                )


class TestProxyServicer(object):
    """The greeting service definition.
    """

    def StartTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestProxyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartTest': grpc.unary_stream_rpc_method_handler(
                    servicer.StartTest,
                    request_deserializer=lite__pb2.TestRequest.FromString,
                    response_serializer=lite__pb2.TestReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'liteproxy.TestProxy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestProxy(object):
    """The greeting service definition.
    """

    @staticmethod
    def StartTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/liteproxy.TestProxy/StartTest',
            lite__pb2.TestRequest.SerializeToString,
            lite__pb2.TestReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
